Portfolio-submission/online_counseling_platform_submission/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('regist/', views.regist, name='regist'),
    path('counselor_regist/', views.counselor_regist, name='counselor_regist'),
    path('counselor_login/', views.counselor_login, name='counselor_login'),
    path('counselor_logout/', views.counselor_logout, name='counselor_logout'),
    path('counselor_edit/', views.counselor_edit, name='counselor_edit'),
    path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_edit/', views.user_edit, name='user_edit'),
    path('change_password/', views.change_password, name='change_password'),
    path('counselor_profile/', views.counselor_profile, name='counselor_profile')
]

Portfolio-submission/online_counseling_platform_submission/boards/urls.py
from django.urls import path
from . import views
# from .views import theme_list #新規追加

app_name = 'boards'

urlpatterns = [
    path('create_theme/', views.create_theme, name='create_theme'),
    path('list_themes/', views.list_themes, name='list_themes'),
    path('edit_theme/<int:id>/', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>/', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>/', views.post_comments, name='post_comments'),
    path('save_comment/', views.save_comment, name='save_comment'),
    path('counselor_list/', views.counselor_list, name='counselor_list'),
    path('counselor_profile/', views.counselor_profile, name='counselor_profile'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='comment_delete'),
    path('upload_sample/', views.upload_sample, name='upload_sample'),
    path('upload_model_form/', views.upload_model_form, name='upload_model_form'),
    path('comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('select_counselor/<int:counselor_id>/', views.select_counselor, name='select_counselor'),
    path('deselect_counselor/', views.deselect_counselor, name='deselect_counselor'),
    # path('themes/', theme_list, name='theme_list'),#新規追加
    path('deselect_counselor/<int:counselor_id>/', views.deselect_counselor, name='deselect_counselor'),

    path('themes/', views.theme_list, name='theme_list'),#新規追加
    path('theme_list/', views.theme_list, name='theme_list'),#新規追加
]

Portfolio-submission/online_counseling_platform_submission/function_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('accounts:user_login', permanent=False)),  # リダイレクト先を'user_login'に変更
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Debugモードの時に静的ファイルとメディアファイルを提供する設定を追加
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

# カスタム404エラーページのハンドラーを設定
handler404 = show_error_page

Portfolio-submission/online_counseling_platform_submission/accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password
from .models import Counselor

class RegistForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

    class Meta():
        model = Users
        fields = ('username', 'age', 'email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')

    def save(self, commit=False):
        user =super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

class CounselorRegistForm(RegistForm):
    username = forms.CharField(label='カウンセラーネーム')

    class Meta(RegistForm.Meta):
        model = Counselor
        fields = ('username', 'age', 'email', 'password')

class UserEditForm(forms.ModelForm):
    username = forms.CharField(label='ユーザーネーム')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    picture = forms.FileField(label='写真', required=False)
    picture2 = forms.ImageField(label='新しい写真', required=False)
    introduction = forms.CharField(label='自己紹介', required=False, widget=forms.Textarea)
    counselor = forms.ModelChoiceField(queryset=Counselor.objects.all(), required=False, label='カウンセラー') #ユーザーはフォームでカウンセラーを選択できるようになりますが、必須ではないため、選択しなくてもフォームを提出できます。

    class Meta:
        model = Users
        fields = ('username', 'age', 'email', 'picture', 'picture2', 'introduction', 'counselor')

class CounselorEditForm(forms.ModelForm):
    username = forms.CharField(label='カウンセラーネーム')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    picture = forms.FileField(label='写真', required=False)
    picture2 = forms.ImageField(label='新しい写真', required=False)
    introduction = forms.CharField(label='自己紹介', required=False, widget=forms.Textarea)
    qualifications = forms.CharField(label='資格', required=False)
    is_counselor = forms.BooleanField(label='カウンセラーとしてログイン中', required=False)

    class Meta:
        model = Counselor
        fields = ('username', 'age', 'email', 'picture', 'picture2', 'introduction', 'qualifications', 'is_counselor')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            # インスタンスが存在する場合は、その値を初期値として設定する
            self.fields['is_counselor'].initial = instance.user.is_counselor if hasattr(instance, 'user') else False
        # is_counselor フィールドを無効化しない
        if 'is_counselor' in self.fields:
            self.fields['is_counselor'].disabled = False

    def save(self, commit=True):
        # フォームが保存された後にインスタンスを再初期化する
        instance = super().save(commit=False)
        # インスタンスのuser属性のis_counselorフィールドを更新
        if hasattr(instance, 'user'):
            instance.user.is_counselor = self.cleaned_data['is_counselor']
            instance.user.save()
        if commit:
            instance.save()

        # 保存後のインスタンスの値を反映してフォームを再初期化する
        instance.refresh_from_db()  # インスタンスをデータベースから最新の情報でリフレッシュ
        self.initial['is_counselor'] = instance.user.is_counselor if hasattr(instance, 'user') else False
        self.fields['is_counselor'].initial = instance.user.is_counselor if hasattr(instance, 'user') else False

        return instance

class LoginForm(forms.Form):
    email = forms.CharField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())

class CounselorLoginForm(forms.Form):
    email = forms.CharField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())

class PasswordChangeForm(forms.ModelForm):

    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

    class Meta():
        model = Users
        fields = ('password', )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

class CounselorPasswordChangeForm(forms.ModelForm):

    password = forms.CharField(label='新しいパスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='新しいパスワード再入力', widget=forms.PasswordInput())

    class Meta:
        model = Counselor
        fields = ('password', )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')

    def save(self, commit=True):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

Portfolio-submission/online_counseling_platform_submission/accounts/views.py
from django.shortcuts import render, redirect
from . import forms
from django.core.exceptions import ValidationError
from .models import UserActivateTokens
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render
from .models import Users
from .models import Counselor

@login_required #記載内容のバックアップです! この記載内容に戻りましょう!
def counselor_profile(request):
    user_lists = []
    counselor_lists = []
    if isinstance(request.user, Users):
        user_lists = Users.objects.filter(id=request.user.id) # type: ignore
    else:
        counselor_lists = Counselor.objects.filter(id=request.user.id)
    return render(request, 'accounts/counselor_profile.html', {
        'user_lists':user_lists, 'counselor_lists':counselor_lists,
    'user': request.user})

# from django.contrib.auth.decorators import login_required
# from django.shortcuts import render, redirect
# from .models import Users, Counselor

# @login_required
# def counselor_profile(request):
#     user_lists = []
#     counselor_lists = []

#     if hasattr(request.user, 'is_counselor') and request.user.is_counselor:  # カウンセラーがログインしている場合
#         counselor = request.user
#         user_lists = Users.objects.filter(counselor=counselor)  # ログインしているカウンセラーに関連するユーザーを取得
#         counselor_lists = [counselor]
#     else:  # ユーザーがログインしている場合
#         user = request.user
#         counselor = user.counselor if hasattr(user, 'counselor') else None
#         if counselor:
#             user_lists = [user]  # 契約しているユーザーの情報を表示
#             counselor_lists = [counselor]  # 契約しているカウンセラーの情報を表示
#         else:
#             user_lists = [user]  # カウンセラーがない場合は、ユーザー自身の情報を表示
#             counselor_lists = []

#     return render(request, 'accounts/counselor_profile.html', {
#         'user_lists': user_lists,
#         'counselor_lists': counselor_lists,
#         'user': request.user
#     })

@login_required #記載内容のバックアップです! この記載内容に戻りましょう!
def counselor_menu(request):
    if isinstance(request.user, Users):
        user_type = 'User'
    else:
        user_type = 'Counselor'
    return render(request, 'base.html', {
        'user_type': user_type})

def home(request):
    return render(
        request, 'accounts/home.html'
    )

def regist(request):
    regist_form = forms.RegistForm(request.POST or None)
    if regist_form.is_valid():
        try:
            regist_form.save()
            return redirect('accounts:home')
        except ValidationError as e:
            regist_form.add_error('password', e)
    return render(
        request, 'accounts/regist.html', context={
            'regist_form': regist_form,
        }
    )

def counselor_regist(request):
    counselor_regist_form = forms.CounselorRegistForm(request.POST or None)
    if request.method == 'POST':
        if counselor_regist_form.is_valid():
            try:
                counselor_regist_form.save()
                return redirect('accounts:home')
            except ValidationError as e:
                counselor_regist_form.add_error('password', e)
    return render(
        request, 'accounts/counselor_regist.html', context={
            'counselor_regist_form': counselor_regist_form,
        }
    )

def activate_user(request, token):
    user_activate_token = UserActivateTokens.objects.activate_user_by_token(token) # type: ignore
    return render(
        request, 'accounts/activate_user.html'
    )

def user_login(request):
    login_form = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, 'ログイン完了しました。')
                return redirect('accounts:home')
                # return redirect('boards:counselor_list')
            else:
                messages.warning(request, 'ユーザがアクティブでありません')
        else:
            messages.warning(request, 'ユーザがパスワードが間違っています' )
    return render(
        request, 'accounts/user_login.html', context={
            'login_form':login_form,
        }
    )

def counselor_login(request): #記載内容のバックアップです!
    counselor_login_form = forms.CounselorLoginForm(request.POST or None)
    if request.method == 'POST':
        if counselor_login_form.is_valid():
            email = counselor_login_form.cleaned_data.get('email')
            password = counselor_login_form.cleaned_data.get('password')
            counselor = authenticate(request, email=email, password=password)
            if counselor:
                if counselor.is_active:
                    login(request, counselor)
                    messages.success(request, 'ログイン完了しました。')
                    return redirect('accounts:home')
                    # return redirect('boards:counselor_list')
                else:
                    messages.warning(request, 'カウンセラーがアクティブでありません')
            else:
                messages.warning(request, 'カウンセラーのメールアドレスまたはパスワードが間違っています')
    return render(
        request, 'accounts/counselor_login.html', context={
            'counselor_login_form': counselor_login_form,
        }
    )

@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'ログアウトしました')
    return redirect('accounts:user_login')

@login_required
def counselor_logout(request):
    logout(request)
    messages.success(request, 'ログアウトしました')
    return redirect('accounts:counselor_login')

@login_required # type: ignore
def user_edit(request):
    user_edit_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance=request.user)
    if user_edit_form.is_valid():
        messages.success(request, '更新完了しました。')
        user_edit_form.save()
    return render(request, 'accounts/user_edit.html', context={
        'user_edit_form': user_edit_form,
    })

@login_required  # type: ignore #この記載内容に戻りましょう!
def counselor_edit(request):
    counselor_edit_form = forms.CounselorEditForm(request.POST or None, request.FILES or None, instance=request.user)
    if request.method == 'POST':
        if counselor_edit_form.is_valid():
            counselor_edit_form.save()
            messages.success(request, '更新完了しました。')
            return redirect('accounts:counselor_edit')
    return render(request, 'accounts/counselor_edit.html', context={
        'counselor_edit_form': counselor_edit_form,
    })

@login_required  # type: ignore
def change_password(request):
    password_change_form = forms.PasswordChangeForm(request.POST or None, instance=request.user)
    if password_change_form.is_valid():
        try:
            password_change_form.save()
            messages.success(request, 'パスワード更新完了しました。')
            update_session_auth_hash(request, request.user)
        except ValidationError as e:
            password_change_form.add_error('password', e)
    return render(
        request, 'accounts/change_password.html', context={
            'password_change_form': password_change_form,
        }
    )

def show_error_page(request, exception):
    return render(
        request, '404.html'
    )

Portfolio-submission/online_counseling_platform_submission/templates/accounts/activate_user.html
{% extends "base.html" %}
{% block content %}
ユーザーを有効化しました
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST">
{% csrf_token %}
{{ password_change_form.as_p }}
<input type="submit" value="パスワード更新">
</form>
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/counselor_edit.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ counselor_edit_form.as_p }}
    <input type="submit" value="更新">
</form>
<a href="{% url 'accounts:change_password' %}">パスワード変更</a>

{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/counselor_login.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ counselor_login_form.as_p }}
    <input type="submit" value="ログイン">
</form>
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/counselor_regist.html
{% extends "base.html" %}
{% block content %}
<h2>カウンセラー登録</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ counselor_regist_form.as_p }}
    <input type="submit" value="カウンセラー登録">
</form>
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}

<div class="text-center">
    <h1>オンラインカウンセリングサービスへようこそ！</h1>
</div>

<div class="text-center mt-2">
    <h3>このアプリでは以下のことができます!</h3>
</div>

<div class="text-center mt-2">
    <p><strong>匿名で安全なカウンセリング：</strong>あなたのプライバシーを守りながら、安心してカウンセリングを受けることができます。</p>
    <p><strong>リアルタイムのチャットサポート：</strong>専門のカウンセラーとリアルタイムでチャットを通じて対話し、即時にサポートを受けられます。</p>
    <p><strong>柔軟なスケジュール：</strong>忙しい生活の中でも、時間や場所を選ばずにカウンセリングを利用できます。</p>
    <p><strong>チャットログの記録と管理：</strong>カウンセリングの内容はすべて記録され、いつでも振り返ることが可能です。</p>
    <p><strong>メッセージの削除：</strong>送信したメッセージを削除する機能を備えています。</p>
</div>

<div class="text-center mt-2">
    <h4>下の画像はカウンセリング例です!</h4>
    <p>下記の画像は、実際にカウンセリングが行われる様子を示した例です。</p>
    <p>ユーザーとカウンセラーがどのようにチャットを通じてコミュニケーションを取るかをご覧いただけます。</p>
</div>

<style>
    .center-image-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 50vh;
        margin-top: 1rem; /* 画像の上の余白を少なくする */
    }
    .center-image {
        max-width: 100%;
        max-height: 100%;
    }
</style>

<div class="center-image-container">
    <img class="center-image" src="{% static 'images/smple8-img.jpg' %}" alt="">
</div>


<nav class="navbar navbar-expand-lg navbar-light bg-light flex-column">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">メインメニューへ</a>
    {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'boards:list_themes' %}">チャット制作画面へ</a>
        <a class="navbar-brand" href="{% url 'accounts:counselor_profile' %}">プロフィール画面へ</a>
        <a class="navbar-brand" href="{% url 'boards:counselor_list' %}">カウンセラー一覧画面へ</a>
        <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
    {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
    {% endif %}
</nav>

{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/regist.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
{% csrf_token %}
{{ regist_form.as_p }}
<input type="submit" value="ユーザー登録">
</form>
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/user_edit.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_edit_form.as_p }}
    <input type="submit" value="更新">
</form>
<a href="{% url 'accounts:change_password' %}">パスワード変更</a>

{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/accounts/user_login.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ login_form.as_p }}
    <input type="submit" value="ログイン">
</form>
{% endblock %}