Portfolio-submission/online_counseling_platform_submission/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('regist/', views.regist, name='regist'),
    path('counselor_regist/', views.counselor_regist, name='counselor_regist'),
    path('counselor_login/', views.counselor_login, name='counselor_login'),
    path('counselor_logout/', views.counselor_logout, name='counselor_logout'),
    path('counselor_edit/', views.counselor_edit, name='counselor_edit'),
    path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_edit/', views.user_edit, name='user_edit'),
    path('change_password/', views.change_password, name='change_password'),
    path('counselor_profile/', views.counselor_profile, name='counselor_profile')
]

Portfolio-submission/online_counseling_platform_submission/boards/urls.py
from django.urls import path
from . import views
# from .views import theme_list #新規追加

app_name = 'boards'

urlpatterns = [
    path('create_theme/', views.create_theme, name='create_theme'),
    path('list_themes/', views.list_themes, name='list_themes'),
    path('edit_theme/<int:id>/', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>/', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>/', views.post_comments, name='post_comments'),
    path('save_comment/', views.save_comment, name='save_comment'),
    path('counselor_list/', views.counselor_list, name='counselor_list'),
    path('counselor_profile/', views.counselor_profile, name='counselor_profile'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='comment_delete'),
    path('upload_sample/', views.upload_sample, name='upload_sample'),
    path('upload_model_form/', views.upload_model_form, name='upload_model_form'),
    path('comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('select_counselor/<int:counselor_id>/', views.select_counselor, name='select_counselor'),
    path('deselect_counselor/', views.deselect_counselor, name='deselect_counselor'),
    # path('themes/', theme_list, name='theme_list'),#新規追加
    path('deselect_counselor/<int:counselor_id>/', views.deselect_counselor, name='deselect_counselor'),

    path('themes/', views.theme_list, name='theme_list'),#新規追加
    path('theme_list/', views.theme_list, name='theme_list'),#新規追加
]

Portfolio-submission/online_counseling_platform_submission/function_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('accounts:user_login', permanent=False)),  # リダイレクト先を'user_login'に変更
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Debugモードの時に静的ファイルとメディアファイルを提供する設定を追加
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

# カスタム404エラーページのハンドラーを設定
handler404 = show_error_page

Portfolio-submission/online_counseling_platform_submission/boards/models.py
from django.db import models
from accounts.models import Counselor  # accountsアプリのCounselorモデルをインポート #記載内容の追加です!
from accounts.models import Users, Counselor

# class ThemesManager(models.Manager):

#     def fetch_all_themes(self):
#         return self.order_by('id').all()

class ThemesManager(models.Manager):
    def fetch_all_themes(self):
        return self.filter(is_deleted=False).order_by('id')

class Themes(models.Model): #記載内容のバックアップです！

    title = models.CharField(max_length=255)
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE)
    counselor = models.ForeignKey(Counselor, on_delete=models.CASCADE, related_name='themes', null=True, blank=True)  # Counselorモデルを関連付ける #記載内容の追加です!
    is_deleted = models.BooleanField(default=False)  # 論理削除フラグ

    objects = ThemesManager()

    class Meta:
        db_table = 'themes'

    def __str__(self):
        return self.title

# class CommentsManager(models.Manager):
#     def fetch_by_theme_id(self, theme_id):
#         return self.filter(theme_id=theme_id).order_by('id').all()

class CommentsManager(models.Manager):
    def fetch_by_theme_id(self, theme_id):
        return self.filter(theme_id=theme_id, is_deleted=False).order_by('id')

class Comments(models.Model):
    comment = models.CharField(max_length=1000)
    user = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True)
    theme = models.ForeignKey('Themes', on_delete=models.CASCADE)
    counselor = models.ForeignKey(Counselor, on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    is_deleted = models.BooleanField(default=False)  # 論理削除フラグ

    objects = CommentsManager()

    class Meta:
        db_table = 'comments'

    def __str__(self):
        return self.comment

class Counselors(models.Model): #記載内容のバックアップです！
    name = models.CharField(max_length=255)
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE)

    class Meta:
        db_table = 'counselors'

    def __str__(self):
        return self.name

class User(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    picture = models.FileField(upload_to='picture/')

Portfolio-submission/online_counseling_platform_submission/boards/forms.py
from django import forms
from .models import Themes, Comments
from .models import User
from accounts.models import Users, Counselor

class CreateThemeForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')

    class Meta:
        model = Themes
        fields = ('title',)

class DeleteThemeForm(forms.ModelForm):

    class Meta:
        model = Themes
        fields = []

class PostCommentForm(forms.ModelForm):
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={'rows': 5, 'cols': 60}))

    class Meta:
        model = Comments
        fields = ('comment', )

class UserInfo(forms.Form): #不要の場合は削除して大丈夫です！
    name = forms.CharField()
    age = forms.IntegerField()
    mail = forms.EmailField()

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

Portfolio-submission/online_counseling_platform_submission/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Themes, Comments
from django.http import Http404
from django.core.cache import cache
from django.http import JsonResponse
from .models import Themes, Comments, Counselors
import os
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.http import Http404
from django.contrib import messages
from .models import Comments
from .forms import PostCommentForm
from django.shortcuts import render
from .models import Counselors
from accounts.models import Counselor, Users
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Themes
from .forms import CreateThemeForm
from django.core.cache import cache
from .models import Themes, Comments
from accounts.models import Users, Counselor
from django.utils.functional import SimpleLazyObject
from django.shortcuts import redirect
from .models import Counselor

@login_required #記載内容のバックアップです！ この記載内容戻りましょう!
def theme_list(request):
    # ログインしているユーザーが作成していないテーマを取得
    themes = Themes.objects.exclude(user=request.user)
    # ログインしているユーザーが作成したテーマを取得
    themes = Themes.objects.filter(user=request.user)
    return render(request, 'boards/list_themes.html', {
        'themes': themes,
    })

# @login_required #記載内容のバックアップです！ この記載内容戻りましょう!
# def theme_list(request):
#     # ログインしているユーザーが作成していないテーマを取得
#     themes = Themes.objects.exclude(user=request.user)
#     # ログインしているユーザーが作成したテーマを取得
#     themes = Themes.objects.filter(user=request.user)
#     return render(request, 'boards/list_themes.html', {
#         'themes': themes,
#     })

# @login_required  #記載内容のバックアップです！
# def theme_list(request):
#     if isinstance(request.user, Counselor):
#         # カウンセラーがログインしている場合
#         # カウンセラーが契約している利用者を取得
#         users = Users.objects.filter(counselor=request.user)
#         print(users)
#         # 契約している利用者が作成したテーマのみを取得
#         themes = Themes.objects.filter(user__in=users).distinct()  # distinct() を追加
#         print(themes)
#     elif isinstance(request.user, Users):
#         # 一般ユーザーがログインしている場合
#         themes = Themes.objects.filter(user=request.user)
#     else:
#         # その他の場合は空のテーマリスト
#         themes = Themes.objects.none()

#     return render(request, 'boards/list_themes.html', {
#         'themes': themes,
#     })

@login_required #記載内容のバックアップです！
def counselor_list(request):
    user = request.user
    if isinstance(user, Counselor):
        user_type = 'Counselor'
    else:
        user_type = 'User'
    counselors = Counselor.objects.all()
    context = {
        'counselors': counselors,
        'user_type': user_type,
        'current_user_email': user.email,  # ログインユーザーのメールアドレスをコンテキストに追加
    }
    return render(request, 'boards/counselor_list.html', context)

# @login_required #記載内容のバックアップです！ この記載内容戻りましょう!
# def select_counselor(request, counselor_id):
#     user = request.user
#     counselor = get_object_or_404(Counselor, id=counselor_id)
#     user.counselor = counselor
#     user.save()
#     messages.success(request, f'{counselor.username}さんがあなたのカウンセラーに選ばれました。')
#     return (redirect('boards:list_themes'))

@login_required #既に他のカウンセラーと契約中です。契約を解除してから新しいカウンセラーを選択してください。と表示されます！
def select_counselor(request, counselor_id):
    user = request.user
    counselor = get_object_or_404(Counselor, id=counselor_id)

    # ユーザーが既に契約中のカウンセラーがいる場合は契約を許可しない
    if user.counselor:
        messages.error(request, '既に他のカウンセラーと契約中です。契約を解除してから新しいカウンセラーを選択してください。')
        return redirect('boards:counselor_list')

    user.counselor = counselor
    user.save()
    messages.success(request, f'{counselor.username}さんがあなたのカウンセラーに選ばれました。')
    return redirect('boards:list_themes')


# @login_required
# def select_counselor(request, counselor_id):
#     user = request.user
#     counselor = get_object_or_404(Counselor, id=counselor_id)
#     user.counselor = counselor
#     user.save()
#     messages.success(request, f'{counselor.username}さんがあなたのカウンセラーに選ばれました。')
#     return redirect('boards:list_themes', counselor_id=counselor.id) # type: ignore


# @login_required #記載内容のバックアップです！
# def deselect_counselor(request):
#     if request.method == 'POST':  # POSTメソッドをチェックする
#         user = request.user
#         user.counselor = None
#         user.save()
#         return redirect('accounts:home')  # リダイレクト先のURLが正しいか確認
#     return redirect('accounts:home')  # GETリクエストの場合のリダイレクト先を指定

# @login_required #記載内容のバックアップです！ この記載内容戻りましょう!
# def deselect_counselor(request, counselor_id):
#     counselor = get_object_or_404(Counselor, id=counselor_id)
#     if request.method == 'POST':
#         request.user.counselor = None
#         request.user.save()
#         return redirect('boards:counselor_list')
#     return render(request, 'boards/counselor_list.html', {'counselors': Counselor.objects.all()})

# @login_required #記載内容のバックアップです！ 問題や不具合が発生してした場合はこの記載内容に戻りましょう!
# def deselect_counselor(request, counselor_id):
#     user = request.user
#     counselor = get_object_or_404(Counselor, id=counselor_id)

#     # ユーザーが現在契約中のカウンセラーであることを確認
#     if user.counselor != counselor:
#         messages.error(request, 'このカウンセラーとは契約していません。')
#         return redirect('boards:counselor_list')

#     if request.method == 'POST':
#         user.counselor = None
#         user.save()
#         messages.success(request, f'{counselor.username}さんとの契約を解除しました。')
#         return redirect('boards:counselor_list')

#     return render(request, 'boards/counselor_list.html', {'counselors': Counselor.objects.all()})

# @login_required#記載内容のバックアップです！ 問題や不具合が発生してした場合はこの記載内容に戻りましょう!
# def deselect_counselor(request, counselor_id):
#     user = request.user
#     counselor = get_object_or_404(Counselor, id=counselor_id)

#     # ユーザーが現在契約中のカウンセラーであることを確認
#     if user.counselor != counselor:
#         messages.error(request, 'このカウンセラーとは契約していません。')
#         return redirect('boards:counselor_list')

#     if request.method == 'POST':
#         # カウンセラーとの契約を解除
#         user.counselor = None
#         user.save()

#         # 契約終了後にカウンセラーとの関連するテーマを論理削除
#         user.themes_set.filter(counselor=counselor, is_deleted=False).update(is_deleted=True)

#         messages.success(request, f'{counselor.username}さんとの契約を解除しました。')
#         return redirect('boards:counselor_list')

#     return render(request, 'boards/counselor_list.html', {'counselors': Counselor.objects.all()})

@login_required
def deselect_counselor(request, counselor_id):
    user = request.user
    counselor = get_object_or_404(Counselor, id=counselor_id)

    # ユーザーが現在契約中のカウンセラーであることを確認
    if user.counselor != counselor:
        messages.error(request, 'このカウンセラーとは契約していません。')
        return redirect('boards:counselor_list')

    if request.method == 'POST':
        # カウンセラーとの契約を解除
        user.counselor = None
        user.save()

        # 契約終了後にカウンセラーとの関連するテーマを論理削除
        user.themes_set.filter(counselor=counselor, is_deleted=False).update(is_deleted=True)

        # 関連するコメントの論理削除（追加）
        user.comments_set.filter(theme__counselor=counselor, is_deleted=False).update(is_deleted=True)

        messages.success(request, f'{counselor.username}さんとの契約を解除しました。')
        return redirect('boards:counselor_list')

    return render(request, 'boards/counselor_list.html', {'counselors': Counselor.objects.all()})

# @login_required#ユーザー側がログインしてしても利用可能です！カウンセラー側がログインしても利用できます！ この記載内容に戻りましょう!
# def edit_comment(request, comment_id):
#     comment = get_object_or_404(Comments, id=comment_id)

#     # Ensure only the owner of the comment or a counselor can edit it
#     if request.user.is_authenticated:
#         if isinstance(request.user, Counselor):
#             # Check if the counselor is associated with a user
#             try:
#                 user = Users.objects.get(counselor=request.user)
#             except Users.DoesNotExist:
#                 user = None

#             if comment.counselor != request.user and comment.user != user:
#                 raise Http404
#         elif comment.user != request.user:
#             raise Http404
#     else:
#         raise Http404

#     edit_comment_form = PostCommentForm(request.POST or None, instance=comment)
#     if edit_comment_form.is_valid():
#         edit_comment_form.save()
#         messages.success(request, 'コメントを更新しました。')
#         return redirect('boards:post_comments', theme_id=comment.theme.id)

#     return render(
#         request, 'boards/edit_comment.html', context={
#             'edit_comment_form': edit_comment_form,
#             'comment': comment,
#         }
#     )

@login_required  # ユーザー側がログインしていても利用可能です。カウンセラー側がログインしても利用できます。
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comments, id=comment_id)

    # Ensure only the owner of the comment or a counselor can edit it
    if request.user.is_authenticated:
        if isinstance(request.user, Counselor):
            # Check if the counselor is associated with a user
            users = Users.objects.filter(counselor=request.user)

            if users.exists():
                user = users.first()
            else:
                user = None

            if comment.counselor != request.user and comment.user != user:
                raise Http404
        elif comment.user != request.user:
            raise Http404
    else:
        raise Http404

    edit_comment_form = PostCommentForm(request.POST or None, instance=comment)
    if edit_comment_form.is_valid():
        edit_comment_form.save()
        messages.success(request, 'コメントを更新しました。')
        return redirect('boards:post_comments', theme_id=comment.theme.id)

    return render(
        request, 'boards/edit_comment.html', context={
            'edit_comment_form': edit_comment_form,
            'comment': comment,
        }
    )


@login_required
def create_theme(request):
    if request.user.is_authenticated:

Portfolio-submission/online_counseling_platform_submission/templates/boards/counselor_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}

<div class="text-center">
    <h1>カウンセラー一覧画面</h1>
</div>

{% for counselor in counselors %}
<div class="counselor-container">
    <div class="image-container">
    {% if counselor.picture2 %}
        <img src="{{ counselor.picture2.url }}" alt="{{ counselor.name }}" width="300" height="300">
    {% endif %}
    </div>
    <div class="info-block">
        <h2>{{ counselor.username }}</h2>
        <p>{{ counselor.introduction }}</p>

        {% if request.user.is_authenticated %}
            {% if request.user.is_counselor %}
                <!-- カウンセラーがログインしている場合、「選択」リンクを表示しない -->
                {% if request.user.id != counselor.id %}
                    <!-- 他のカウンセラーの「選択」リンクを非表示 -->
                {% endif %}
            {% else %}
                <!-- ユーザーがログインしている場合、選択リンクを表示 -->
                <a href="{% url 'boards:select_counselor' counselor.id %}">選択</a>
            {% endif %}
        {% else %}
            <!-- 未ログイン状態では「選択」リンクを表示 -->
            <a href="{% url 'boards:select_counselor' counselor.id %}">選択</a>
        {% endif %}

        {% if user_type == 'User' %}
        {% if request.user.counselor is None %}
        <form method="POST" action="{% url 'boards:deselect_counselor' counselor.id %}">
        {% csrf_token %}
        </form>
        {% endif %}
        {% endif %}
    </div>
</div>
{% endfor %}

{% block extra_styles %}
<style>
    .counselor-container {
        display: flex;
        align-items: center;
        justify-content: flex-start; /* 左寄せ */
        margin: 20px auto;
    }
    .image-container {
        flex: 0 0 auto;
    }
    .info-block {
        padding: 10px; /* 内側の余白を小さく */
        border: 1px solid #000;
        background-color: #f0f0f0;
        text-align: left;
        margin-left: 20px; /* 画像とテキストの間の余白 */
        width: 300px; /* 幅を300ピクセルに設定 */
    }
    .text-center {
        text-align: center;
    }
</style>
{% endblock %}

<nav class="navbar navbar-expand-lg navbar-light bg-light flex-column">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">メインメニューへ</a>
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'accounts:counselor_profile' %}">プロフィール画面へ</a>
    {% else %}
    {% endif %}
</nav>

{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/boards/edit_theme.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<h3>チャット画面編集</h3>

<form method="post" novalidate>
    {% csrf_token %}
    {{ edit_theme_form.as_p }}
    <button type="submit">更新する</button>
</form>

{% if user_type == 'Counselor' or user_type == 'User' %}
    <form method="post" action="{% url 'boards:delete_theme' id=id %}">
        {% csrf_token %}
        <button type="submit">チャット画面を削除する</button>
    </form>
{% endif %}
{% endblock %}


{% comment %} {% extends "base.html" %}
{% block content %}
<h3>チャット編集画面</h3>
<form method="POST">
{% csrf_token %}
{{ edit_theme_form.as_p }}
<input type="submit" value="更新">
</form>
<p><a class="navbar-brand" href="{% url 'boards:delete_theme' id=id %}">削除する</a></p>
{% endblock %} {% endcomment %}

Portfolio-submission/online_counseling_platform_submission/templates/boards/list_themes.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<h3>チャット画面一覧</h3>

{% if request.user.is_authenticated %}
    {% if not request.user.is_counselor and request.user.counselor %}
        <p><a class="navbar-brand" href="{% url 'boards:create_theme' %}">チャット画面を新たに作成する</a></p>
    {% else %}
        <p>カウンセラーと契約するとチャット画面を作成できるようになります</p>
    {% endif %}
{% endif %}

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>タイトル</th>
            <th>チャット作成者</th>
        </tr>
    </thead>
    <tbody>
    {% for theme in themes %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'boards:post_comments' theme_id=theme.id %}">{{ theme.title }}</a></td>
        <td>
            {% if not request.user.is_counselor %}
                <a href="{% url 'boards:edit_theme' id=theme.id %}">{{ theme.user.username }}</a>
            {% else %}
                {{ theme.user.username }}
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/boards/post_comments.html
{% extends "base.html" %}
{% block content %}
<h3>{{ theme.title }}</h3>

{% for comment in comments %}
<div class="col-1 offset-1">
    {% if comment.user %}
        {% if comment.user.picture %}
            <img style="float:left;" width="50px" height="50px" src="{{ comment.user.picture.url }}">
        {% endif %}
    {% elif comment.counselor %}
        {% if comment.counselor.picture %}
            <img style="float:left;" width="50px" height="50px" src="{{ comment.counselor.picture.url }}">
        {% endif %}
    {% endif %}
</div>
<div class="col-8 offset-2">
    {% if comment.user %}
        <p>名前: {{ comment.user.username }}</p>
    {% elif comment.counselor %}
        <p>カウンセラー名: {{ comment.counselor.username }}</p>
    {% endif %}
    <p>{{ comment.comment | linebreaks }}</p>
    {% if comment.user == user or comment.counselor == user %}
    {% comment %} {% if comment.user == user or comment.counselor == counselor %} {% endcomment %}
        <a href="{% url 'boards:comment_delete' comment.pk %}">コメント削除</a>
        <a href="{% url 'boards:edit_comment' comment.pk %}">コメント編集</a>
    {% endif %}
</div>
<div class="col-10 offset-1">
<hr>
</div>
{% endfor %}

{% if user.is_authenticated %}
<div class="col-4 offset-7">
    <form method="POST">
    {% csrf_token %}
    {{ post_comment_form.as_p }}
    <input type="submit" value="コメント送信">
    </form>
</div>
{% endif %}
{% endblock %}

{% block javascript %}
<nav class="navbar navbar-expand-lg navbar-light bg-light flex-column align-items-end">
    <a class="btn btn-primary mb-2" href="{% url 'accounts:home' %}">メインメニューへ</a>
    <a class="btn btn-primary mb-2" href="{% url 'boards:delete_theme' id=theme.id %}">相談を終了する</a>
</nav>

<script>
{% comment %} 54～60の下記の記載内容に関しては、チャット画面において、コメント送信時にスペースのみの入力を検知し、送信を中止してエラーメッセージを表示する機能を備えています。これにより、誤って無効なコメントが送信されるのを防ぐことができます。 {% endcomment %}
document.querySelector("form").addEventListener("submit", function(event){
    var comment = document.querySelector("#id_comment").value;
    if (!comment.trim()) {
        event.preventDefault(); // フォーム送信を中止
        alert("コメント送信時にスペースのみ登録した際に、【コメントには有効な文字を入力してください。】"); // エラーメッセージを表示
    }
});

$("#save_comment").click(function(){
    var comment = $("#id_comment").val();
    $.ajax({
        url: "{% url 'boards:save_comment' %}",
        type: "GET",
        data: {comment: comment, theme_id: "{{ theme.id }}"},
        dataType: "json",
        success: function(json){
            if(json.message){
                alert(json.message);
            }
        }
    });
});
</script>
{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/boards/upload_file.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="upload_file"><br>
    <input type="submit" value="保存">
    </form>

    {% if uploaded_file_url %}
    <p>保存先: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
    </form>
    {% if user %}
    <p>name: {{ user.name }}</p>
    <p>age: {{ user.age }}</p>
    <img src="{{ user.picture.url }}" style="width: 300px; height: 300px;">
    {% endif %}

    <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>

    <nav class="navbar navbar-expand-lg navbar-light bg-light flex-column">
    <a class="navbar-brand" href="{% url 'boards:list_themes' %}">チャット制作画面へ</a>
    <a class="navbar-brand" href="{% url 'boards:list_themes' %}">チャット制作画面へ</a>
    <a class="navbar-brand" href="{% url 'accounts:home' %}">メインメニューへ</a>
    <a class="navbar-brand" href="{% url 'boards:counselor_profile' %}">プロフィール画面へ</a>
</nav>

{% endblock %}

Portfolio-submission/online_counseling_platform_submission/templates/boards/upload_model_form.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
    </form>
    {% if user %}
    <p>name: {{ user.name }}</p>
    <p>age: {{ user.age }}</p>
    <img src="{{ user.picture.url }}" style="width: 300px; height: 300px;">
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
    </form>
    {% if user2 %}
    <p>name: {{ user.name }}</p>
    <p>age: {{ user.age }}</p>
    <img src="{{ user.picture.url }}" style="width: 300px; height: 300px;">
    {% endif %}

    <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>

    <nav class="navbar navbar-expand-lg navbar-light bg-light flex-column">
    <a class="navbar-brand" href="{% url 'boards:list_themes' %}">チャット制作画面へ</a>
    <a class="navbar-brand" href="{% url 'boards:list_themes' %}">チャット制作画面へ</a>
    <a class="navbar-brand" href="{% url 'accounts:home' %}">メインメニューへ</a>
    <a class="navbar-brand" href="{% url 'boards:counselor_profile' %}">プロフィール画面へ</a>
</nav>

{% endblock %}