Portfolio-submission/online_counseling_platform_submission/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('regist/', views.regist, name='regist'),
    path('counselor_regist/', views.counselor_regist, name='counselor_regist'),
    path('counselor_login/', views.counselor_login, name='counselor_login'),
    path('counselor_logout/', views.counselor_logout, name='counselor_logout'),
    path('counselor_edit/', views.counselor_edit, name='counselor_edit'),
    path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_edit/', views.user_edit, name='user_edit'),
    path('change_password/', views.change_password, name='change_password'),
    path('counselor_profile/', views.counselor_profile, name='counselor_profile')
]

Portfolio-submission/online_counseling_platform_submission/boards/urls.py
from django.urls import path
from . import views
# from .views import theme_list #新規追加

app_name = 'boards'

urlpatterns = [
    path('create_theme/', views.create_theme, name='create_theme'),
    path('list_themes/', views.list_themes, name='list_themes'),
    path('edit_theme/<int:id>/', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>/', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>/', views.post_comments, name='post_comments'),
    path('save_comment/', views.save_comment, name='save_comment'),
    path('counselor_list/', views.counselor_list, name='counselor_list'),
    path('counselor_profile/', views.counselor_profile, name='counselor_profile'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='comment_delete'),
    path('upload_sample/', views.upload_sample, name='upload_sample'),
    path('upload_model_form/', views.upload_model_form, name='upload_model_form'),
    path('comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('select_counselor/<int:counselor_id>/', views.select_counselor, name='select_counselor'),
    path('deselect_counselor/', views.deselect_counselor, name='deselect_counselor'),
    # path('themes/', theme_list, name='theme_list'),#新規追加
    path('deselect_counselor/<int:counselor_id>/', views.deselect_counselor, name='deselect_counselor'),

    path('themes/', views.theme_list, name='theme_list'),#新規追加
    path('theme_list/', views.theme_list, name='theme_list'),#新規追加
]

Portfolio-submission/online_counseling_platform_submission/function_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('accounts:user_login', permanent=False)),  # リダイレクト先を'user_login'に変更
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Debugモードの時に静的ファイルとメディアファイルを提供する設定を追加
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

# カスタム404エラーページのハンドラーを設定
handler404 = show_error_page

Portfolio-submission/online_counseling_platform_submission/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>オンラインカウンセリングプラットフォーム</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">メインメニューへ</a>
    {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'boards:counselor_list' %}">カウンセラー一覧画面へ</a>
        <a class="navbar-brand" href="{% url 'accounts:counselor_profile' %}">プロフィール画面へ</a>
        <a class="navbar-brand" href="{% url 'boards:list_themes' %}">チャット制作画面へ</a>
        <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
    {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
        <a class="navbar-brand" href="{% url 'accounts:counselor_regist' %}">カウンセラー登録</a>
        <a class="navbar-brand" href="{% url 'accounts:counselor_login' %}">カウンセラーログイン</a>
    {% endif %}
</nav>
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}

    </body>
</html>